defaults: &defaults
  HOST: 'https://api.dashamail.com'
  API_KEY: 'fbdc4678093c581b6a41eb1057ca3638'
production:
  <<: *defaults
  API_KEY: 'fbdc4678093c581b6a41eb1057ca3638'
development:
  <<: *defaults
test:
  <<: *defaults
